---
title: "plot_gsea_clr"
output: html_document
date: "2022-11-29"
---

```{r}
library(latex2exp)
library(ggplot2)
source("gsea.R")
```

```{r}
height <- 1.3
text_color <- "#717171"
line_color <- "#cacaca"
point_color_1 <- "black"
point_color_2 <- "black"
#point_color_1 <- "#D81B60"
#point_color_2 <- "#FFC107"

plot_bracket <- function(plot_g, wisker_size, y, x1, x2, text, color="black", text_size=2.5, text_offset=0.05) {
  plot_g <- plot_g + geom_segment(x=x1, xend=x2, y=y, yend=y, color=color)
  plot_g <- plot_g + geom_segment(x=x1, xend=x1, y=y, yend=y-wisker_size, color=color)
  plot_g <- plot_g + geom_segment(x=x2, xend=x2, y=y, yend=y-wisker_size, color=color)
  plot_g <- plot_g + annotate("text", x=x1+(abs(x2-x1)/2), y=y+text_offset, label=text, hjust=0.5, size=text_size, color=color)
  plot_g
}

df <- data.frame(x=c(-0.6,-0.3,0.3,0.6,1.2,1.5,1.8,2.1), label=c("in", "in", "in", "in", "out", "out", "out", "out"))

g <- ggplot(df, aes(x=x, y=height, shape=label))

# Arrow
g <- g + geom_segment(x=-0.9, y=height, xend=2.2, yend=height, arrow = arrow(length = unit(0.03, "npc"), ends="both"), color=line_color) # Arrow
g <- g + geom_point(size=3, stroke=1.4, color=text_color)

# Mean point
g <- g + annotate("point", x=mean(df$x), y=height, color="black", shape=8, size=1.5, stroke=1.25)
g <- g + geom_segment(x=mean(df$x)+0.03, xend=mean(df$x)+0.1, y=height-0.1, yend=height-0.3, arrow=arrow(length = unit(0.03, "npc"), ends="first"), color="black", size=0.35)
g <- g + annotate("text", x=mean(df$x)+0.11, y=height-0.3, hjust=0, label=TeX("$mean(\\theta_1$,...,$\\theta_D)$"), size=3, color="black")

# 0
g <- g + geom_segment(x=0, xend=0, y=height-0.1, yend=height+0.1, color="black")
g <- g + annotate("text", x=0, y=height-0.17, label=0, size=3.5, color="black")

# Arrows and Lines
g <- g + geom_segment(x=mean(df$x), xend=-0.6, y=height+0.25, yend=height+0.25, arrow=arrow(length = unit(0.04, "npc"), ends="last"), color="#D81B60", size=0.75)
g <- g + geom_segment(x=mean(df$x), xend=mean(df$x), y=height+0.08, yend=height+0.25, color="#D81B60", linetype="11", size=0.3)
g <- g + geom_segment(x=-0.6, xend=-0.6, y=height+0.04, yend=height+0.25, color="#D81B60", linetype="11", size=0.3)
g <- g + annotate("text", x=(mean(df$x)-0.6)/2, y=height+0.25+0.125, label=TeX("$\\vartheta_1=\\theta_1-mean(\\theta_1$,...,$\\theta_D)$"), hjust=0.5, size=3, color="#D81B60")

g <- g + geom_segment(x=0, xend=-0.6, y=height-0.35, yend=height-0.35, arrow=arrow(length = unit(0.04, "npc"), ends="last"), color="#1E88E5", size=0.75)
g <- g + geom_segment(x=0, xend=0, y=height-0.25, yend=height-0.35, color="#1E88E5", linetype="11", size=0.3)
g <- g + geom_segment(x=-0.6, xend=-0.6, y=height-0.04, yend=height-0.35, color="#1E88E5", linetype="11", size=0.3)
g <- g + annotate("text", x=(-0.6)/2, y=height-0.35-0.125, label=TeX("$\\theta_1$"), hjust=0.5, size=3, color="#1E88E5")

# Legend
legend_offset <- -0.1
legend_offset_y <- 0.05

g <- g + annotate("point", x=legend_offset-0.5, y=legend_offset_y+0.25, color=text_color, shape=4, size=3, stroke=1.4)
g <- g + annotate("text", x=legend_offset-0.425, y=legend_offset_y+0.25, color=text_color, hjust=0, label="In Set", size=3)

g <- g + annotate("point", x=legend_offset+0, y=legend_offset_y+0.25, color=text_color, shape=21, size=3, stroke=1.4)
g <- g + annotate("text", x=legend_offset+0.075, y=legend_offset_y+0.25, color=text_color, hjust=0, label="Not In Set", size=3)

g <- g + geom_segment(x=legend_offset+0.625, xend=legend_offset+0.775, y=legend_offset_y+0.265, yend=legend_offset_y+0.265, arrow=arrow(length = unit(0.03, "npc"), ends="first"), color="#1E88E5", size=0.25)
g <- g + annotate("text", x=legend_offset+0.7, y=legend_offset_y+0.23, color="#1E88E5", hjust=0, label=TeX("\\theta"), size=1.5)
g <- g + annotate("text", x=legend_offset+0.8, y=legend_offset_y+0.25, color=text_color, hjust=0, label="GSEA-LFC", size=3)

g <- g + geom_segment(x=legend_offset+1.4, xend=legend_offset+1.55, y=legend_offset_y+0.265, yend=legend_offset_y+0.265, arrow=arrow(length = unit(0.03, "npc"), ends="first"), color="#D81B60", size=0.25)
g <- g + annotate("text", x=legend_offset+1.475, y=legend_offset_y+0.23, color="#D81B60", hjust=0, label=TeX("\\vartheta"), size=1.5)
g <- g + annotate("text", x=legend_offset+1.575, y=legend_offset_y+0.25, color=text_color, hjust=0, label="GSEA-CLR", size=3)

# Legend Box
g <- g + geom_rect(xmin=legend_offset-0.6, xmax=legend_offset+2.05, ymin=legend_offset_y+0.125, ymax=legend_offset_y+0.4, color=text_color, alpha=0, size=0.1)

# Settings
g <- g + scale_shape_manual(values=c(4,21))
g <- g + xlim(-1,2.3) + ylim(0.2, 2)

g <- g + theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin=margin(0, 0, 0, 0))
ggsave("figure_gsea_clr_single.png", g, units="in", width=5, height=1.8)
```

```{r}
#color <- "#717171"
text_color <- "#717171"
line_color <- "#cacaca"
point_color_1 <- "#D81B60"
point_color_2 <- "#FFC107"
#color2 <- "black"

x1 <- c(-2,-1,-0.5,-0.2,0.1,0.35,0.65,0.9,1.7,2,2.3,2.7,3.2,3.6,4.2)
labels <- c("out", "in", "in", "in", "in", "in", "out", "in", "out", "out", "out", "out", "out", "out", "out")
cbind(x1, labels)
gsea(x1, which(labels=="in"), iters=10000)
x2 <- x1 - mean(x1)
gsea(x2, which(labels=="in"), iters=10000)

offset_bot <- 0.1
start <- -4.5
end <- 4.5

legend_offset <- 0.2
x_extra <- c() #c(3.8+legend_offset,3.8+legend_offset)
y_extra <- c() #c(0.925, 1.225)
labels_extra <- c() #c("out", "in")

plot_bracket <- function(plot_g, wisker_size, y, x1, x2, text, color="black", text_size=2.5, text_offset=0.05) {
  plot_g <- plot_g + geom_segment(x=x1, xend=x2, y=y, yend=y, color=color)
  plot_g <- plot_g + geom_segment(x=x1, xend=x1, y=y, yend=y-wisker_size, color=color)
  plot_g <- plot_g + geom_segment(x=x2, xend=x2, y=y, yend=y-wisker_size, color=color)
  plot_g <- plot_g + annotate("text", x=x1+(abs(x2-x1)/2), y=y+text_offset, label=text, hjust=0.5, size=text_size, color=color)
  plot_g
}

df <- data.frame(x=c(x1, x2, x_extra), y=c(rep(1.5,length(labels)), rep(offset_bot+0.5,length(labels)), y_extra), l=c(labels, labels, labels_extra))
g <- ggplot(df, aes(x=x,y=y,shape=l,color=l)) + theme_bw() +
    geom_segment(x=start, y=1.5, xend=end, yend=1.5, arrow = arrow(length = unit(0.03, "npc"), ends="both"), color=line_color) +
    geom_segment(x=start, y=offset_bot+0.5, xend=end, yend=offset_bot+0.5, arrow = arrow(length = unit(0.03, "npc"), ends="both"), color=line_color) + # Bottom
    geom_segment(x=0, xend=0, y=1.425, yend=1.575, color=line_color) +
    geom_segment(x=0, xend=0, y=offset_bot+0.425, yend=offset_bot+0.575, color=line_color) + # Bottom
    xlim(start, end) + ylim(0, 2) + geom_point(size=3, stroke=1.4) + scale_color_manual(values=c(point_color_1, point_color_2))

g <- g + annotate("text", x=-1.5, y=1.25, label=TeX("$\\theta_1$"), size=3.5, color=text_color) # Bottom
g <- g + annotate("text", x=-1.8, y=offset_bot+0.1, label=TeX("$\\vartheta_1=\\theta_1-\\frac{1}{D} \\sum_{d=1}^D \\theta_d$"), size=3.5, color=text_color)
g <- g + annotate("text", x=0, y=1.37, label=0, size=3.5, color=line_color) + annotate("text", x=0, y=offset_bot+0.37, label=0, size=3.5, color=line_color) # Top + Bottom
#g <- g + annotate("text", x=4.7+legend_offset,y=y_extra[1], label="Not In Set", size=3)
#g <- g + annotate("text", x=4.4+legend_offset,y=y_extra[2], label="In Set", size=3)

g <- g + geom_segment(x=-1.51, xend=-1.425, y=1.32, yend=1.43, arrow=arrow(length = unit(0.03, "npc"), ends="last"), color=text_color)
g <- g + geom_segment(x=-2.65, xend=-2.4, y=offset_bot+0.17, yend=offset_bot+0.43, arrow=arrow(length = unit(0.03, "npc"), ends="last"), color=text_color) # Bottom
g <- g + scale_shape_manual(values=c(4,21))
#g <- plot_bracket(g, 0.06, 1.625, -0.95, 0.8, expression(paste(italic(p), "=0.052")), color="#717171")
#g <- plot_bracket(g, 0.06, offset_bot+0.625, -1.9, -0.15, expression(paste(italic(p), "=0.025")), color="#717171")
g <- g + annotate("text", x=0, y=1.75, label="~underline('GSEA-LFC: p-value=0.052')", size=4, hjust=0.5, parse=T)
g <- g + annotate("text", x=0, y=0.85, label="~underline('GSEA-CLR: p-value=0.013')", size=4, hjust=0.5, parse=T)

g <- g + theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank())
ggsave("figure_gsea_clr_expl.png", g, units="in", width=5, height=2.8)
g
```